### ISSUE TITLE
couldnt load JSlinkfinder

### ISSUE THREAD

**Issue by akremtechcampus** [InitRoot/BurpJSLinkFinder#1]
couldnt load JSlinkfinder
java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.mke.<init>(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.gc.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by InitRoot** [comment]
Have you setup your Burp Professional with JPython?

**Comment by akremtechcampus** [comment]
its already installed and i used it before with some Extenders

**Comment by InitRoot** [comment]
So googling the issue.. Maybe look here:
https://github.com/bugcrowd/HUNT/issues/50

The user had the same issues, worked for some extensions failed for others.

**Comment by InitRoot** [comment]
> standalone jython. I thought I was, but nope.
> I followed the instructions from there:
> https://support.portswigger.net/customer/portal/questions/17097263-burp-extension-python-import-error
>

**Comment by akremtechcampus** [comment]
thanks i am already working on it

**Comment by InitRoot** [comment]
Great can I close the issue then?

**Comment by akremtechcampus** [comment]
yes you can but its not fixed yet thank you in advance

**Comment by InitRoot** [comment]
I'm keeping open. Please let me know. 
If you can't seem to fix it I'll run some testing an VM's to replicate. Worked fine on my windows and linux machine using the single jar for jpython.

**Comment by jaikishantulswani** [comment]
same issue here, jython is installed and extension is also installed successfully but not showing any log.

**Comment by InitRoot** [comment]
Thanks for trying it out. Can you assist debugging by adding more information. To start off..

- Operating System
- Burp Version
- Screenshots of your single JPython config
- Is the plugin successfully loaded? Any errors?
- Is your scanning scope set to scan passive?
- Is your passive scanner limited to scope?
- Opening tesla.com does not provide any output?

**Comment by ghost** [comment]
hey,i know how to solve this error,
listen,you must put your jython jar file and your plugin together on the system disk or on the system floder.
you can't put them on floder which you built.
