### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by davehardy20** [InitRoot/BurpJSLinkFinder#2]
I have the extension loaded into Burp Pro, I have Jython also. But the BurpJSLinkFinder tab does not populate with any findings.
I have done passive scans of the website, and still not seeing anything in the tab.

I am using Burp Pro 1.7.37

Please advise on the usage of this extension, its a great idea.

Thanks

**Comment by ghost** [comment]
yep, please write the doc man!

**Comment by davehardy20** [comment]
It seems I was too impatient, its working now.
As your ToDo mentions, it needs threading :)

Thanks for this will be useful

Dave
